// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_Farcas_Gherghelas.Data;

#nullable disable

namespace Proiect_Farcas_Gherghelas.Migrations
{
    [DbContext(typeof(Proiect_Farcas_GherghelasContext))]
    [Migration("20231222135207_Inchirieri")]
    partial class Inchirieri
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Proiect_Farcas_Gherghelas.Models.Inchiriere", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Magazin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartieID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PartieID");

                    b.ToTable("Inchiriere");
                });

            modelBuilder.Entity("Proiect_Farcas_Gherghelas.Models.Partie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Partie");
                });

            modelBuilder.Entity("Proiect_Farcas_Gherghelas.Models.Inchiriere", b =>
                {
                    b.HasOne("Proiect_Farcas_Gherghelas.Models.Partie", "Partie")
                        .WithMany()
                        .HasForeignKey("PartieID");

                    b.Navigation("Partie");
                });
#pragma warning restore 612, 618
        }
    }
}
